Sprint 3
iamkirabond/middle.messenger.praktikum.yandex pull request #4
Opened 2021-10-04 20:40 UTC by iamkirabond

2021-10-15 16:21 UTC, nickchamel requested changes
Привет! Есть еще над чем поработать:
При перезагрузке страниц они должны работать (это настройки netlify.toml - нужно чтобы всегд отдавался index.html)
![image](https://user-images.githubusercontent.com/28347933/137519832-e3043b88-864c-41bd-8cfd-ada7db7cf89d.png)
Множественные ошибки в консоли (чаты не работают, сообщения не показываются)
![image](https://user-images.githubusercontent.com/28347933/137520017-44ea174a-a9c6-4ef0-bca0-354cae38c323.png)
Аватар не грузится (ошибки в консоли)
![image](https://user-images.githubusercontent.com/28347933/137520191-3150781a-fec9-4285-9ab4-f15d887bce34.png)
Изменить данные профиля не получается
Перейти назад из профиля не получается
Ошибки не показываются
![image](https://user-images.githubusercontent.com/28347933/137520319-a012966e-9f3a-4ba3-811c-3a25037792d9.png)
Кнопка "авторизоваться не работает"
Проверь, пожалуйста, что весь основной функционал работает перед отправкой на ревью!
Еще стоит отметить что типизации нет совсем, было бы неплохо покрыть код типами.
И тестов маловато, как минимум по заданию нужны еще на компонент и на http сервис
Работу пока вернул

2021-10-15 16:21 UTC, nickchamel commented on .gitignore
> +.DS_Store
1 раз достаточно указать

2021-10-15 16:21 UTC, nickchamel commented on index.html
> +  <title>Yandex Messengerff</title>
случайно?

2021-10-15 16:21 UTC, nickchamel commented on package.json
> +    "ts-node": "^10.3.0"
кроме `handlebars` здесь все devDependencies
`express-handlebars` вроде как не используется, значит можно удалить

2021-10-15 16:21 UTC, nickchamel commented on src/api/auth-api.ts
> +export default class AuthAPI extends BaseAPI {
С помощью наследования можно сократить код
```
import HTTPTransport from './http';

const host = 'https://ya-praktikum.tech/api/v2/';

export default abstract class BaseAPI {
  protected http: HTTPTransport;

  protected constructor(endpoint: string) {
    this.http = new HTTPTransport(host + endpoint);
  }
}
```
```
export default class AuthAPI extends BaseAPI {
  constructor() {
    super('auth')
  }
  ...
```
А так же апи можно сделать синглтонами, нет смысла создавать по несколько экземпляров
`export default new AuthAPI();`

2021-10-15 16:21 UTC, nickchamel commented on src/api/auth-api.ts
> +        console.log(reject);
В `signup` ошибка пробрасывается дальше, в `signin` нет.
Лучше везде пробрасывать, чтобы иметь возможность обработать эту ошибку в UI.
Например фронтенд валидация на форме прошла, на бэке нет - нужно показать это в UI.

И если нет здесь никакой логики по обработке ошибки, то достаточно будет написать
```
return authAPIInstance.post('/signin', { data })
  .then(() => {
    this.getUserInfo();
    router.go('/messenger');
  });
```
и она пробросится дальше, где ее нужно будет отловить (try/catch, .catch)

2021-10-15 16:21 UTC, nickchamel commented on src/api/auth-api.ts
> +    return authAPIInstance.get('/user').then((response:string) => JSON.parse(response));
Логику по парсингу респонса лучше оставить в `HTTPrequest`, чтобы нигде более ее не дублировать

2021-10-15 16:21 UTC, nickchamel commented on src/api/chat-api.ts
> +    return chatAPIInstance.post('/', { data: JSON.stringify({ title }) });
Здесь "стрингифаится" только объект с тайтлом, а сам объект с датой нужно будет "стрингифаить" тоже и желательно это тоже вынести в `HTTPrequest` перед отправкой, чтобы нигде более не дублировать.

2021-10-15 16:21 UTC, nickchamel commented on src/api/chat-api.ts
> +    return chatAPIInstance.delete('/users', { data: JSON.stringify({ users, chatId }) });
Где-то данные прокидываются в св-ве `data`, где-то нет. Лучше привести к одному виду

2021-10-15 16:21 UTC, nickchamel commented on src/api/user-api.ts
> +    console.log(login, { data: JSON.stringify({ login }) });
Логи перед пушем в репозиторий желательно подчищать

2021-10-15 16:21 UTC, nickchamel commented on src/components/chat/ChatCurrent.ts
> +// @ts-ignore
Стоит разобраться что не нравится ТСу с импортом хбса, потому что в каждом файле так писать не классно

2021-10-15 16:21 UTC, nickchamel commented on src/controllers/user-auth.ts
> +    }
У тебя на данный момент `signin` вообще не пробрасывает ошибку, поэтому здесь управление в catch никогда не перейдет.
Из контроллеров тоже лучше ошибку пробрасывать далее и уже в компоненте можно будет ее отловить и отобразить в UI, а не с помощью `alert`

По стрингифаю выше отписал - лучше в едином месте описать эту логику и не дублировать, а у тебя сейчас она еще и по нескольким местам раскидана - в контроллерах/апи

2021-10-15 16:21 UTC, nickchamel commented on src/controllers/user-auth.ts
> +        alert('This email already in use!')
На самом деле далеко не факт что ошибка будет именно такая.
Здесь речь идет о сайнапе. Может поле было неверно заполнено (например банально на фронте и на бэке разные валидации) или такого емейла не существует, а может юзер такой уже есть.
Ошибку нужно показать какая она есть на самом деле

2021-10-15 16:21 UTC, nickchamel commented on src/pages/404/404.ts
> +    console.log(data);
лог

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.scss
> +                border-color: #999999;
цвет можно вынести в переменную к остальным

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.scss
> +                background: #EAEAEA;
и этот, и далее тоже встречаются

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.ts
> +const chatDataRequester = new UserAuthController();
Контроллеры тоже можно сделать синглтонами и экспортить сразу их экземпляры

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.ts
> +        click: event => this.clickHandler(event),
Можно сократить до `click: this.clickHandler,`

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.ts
> +    let modal = document.querySelectorAll('.new-chat-name.modal')[0];
Можно заменить на `querySelector` и тогда не придется работать с массивом

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.ts
> +              })
Чем писать глубокую вложенность `then`, проще использовать async/await
```
promise
  .then(r => {
    promise2
      .then(r => {
        promise3
          .then(r = {
            
          })
      })
  })
```
```
try {
  const r1 = await promise();
  const r2 = await promise2();
  const r3 = await promise3();
} catch {
  ...
}
```
И здесь ты уже сталкиваешься с тем, что везде нужно парсить респонс, поэтому лучше это сделать сразу

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.ts
> +        let clickedId = event.target.closest('.chats-item').dataset.id;
Такие св-ва как `closest` или `nextSibling`/`previousSibling` лучше стараться не использовать, потому что так ты сильно завязываешься на вью слое. То есть если в шаблоне что-то измениться, то код просто перестанет работать

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.ts
> +    .catch(data => console.log(JSON.parse(data.response)));
За отступами лучше следить, чтобы код было проще читать
```
    return chatDataRequester.getChats()
      .then((response) => {
        this.props.chatRooms = JSON.parse(response);
      })
      .catch(data => console.log(JSON.parse(data.response)));
```

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.ts
> +    }) : null;
Можно сократить до 
```
let chatRooms = data.chatRooms?.map((item) => {
  return new ChatItem(item).render()
});
```
если undefined будет достаточно, заместо null

2021-10-15 16:21 UTC, nickchamel commented on src/pages/chats/chats.ts
> +      chatRooms: data.chatRooms ? chatRooms.join('\n') : null,
Вообще вставлять контент чайлд-компонентов это задача класса `Block` и желательно их контент аппендить (`.append()`), чтобы можно было например навешивать обработчики, а не просто вставлять их контент строкой

2021-10-15 16:21 UTC, nickchamel commented on src/pages/profile/profile.ts
> +              let isValid = validationForm(input.value, input.dataset.type);
Если эта функция валидирует инпут, то лучше ее назвать соответсвующе `validateInput`

2021-10-15 16:21 UTC, nickchamel commented on src/pages/profile/profile.ts
> +        })
Лучше здесь просто передеать данные, а в контроллере или в апи-слое добавить необходимые хедеры

2021-10-15 16:21 UTC, nickchamel commented on src/pages/profile/profile.ts
> +        this.props.lastname.data = data.first_name;
lastname = first_name?
И странно что lastname это объект, по идее это должны быть строка

2021-10-15 16:21 UTC, nickchamel commented on src/pages/signIn/signIn.ts
> +import UserAuthController from '../../controllers/user-auth';
Кавычки стоит привести к одному виду

2021-10-15 16:21 UTC, nickchamel commented on src/pages/signUp/signUp.ts
> +                    if(inputs[inputs.length-1].value === inputs[inputs.length-2].value){
Лог можно удалить.
А еще лучше оперировать не позицией инпута в массиве, а атрибутами, например. То есть добавить к каждому инпуту `data-type="email"` и тд. Это будет масштабируемо и не сломает код. Тут у тебя опять же ситуация, что если в шаблоне что-то измениться то код перестанет работать

2021-10-15 16:21 UTC, nickchamel commented on src/templates/Chats/chatRoom.tmpl.ts
> +            <button id="addUserByLogin">Добавить</button>
Кнопкам лучше всегда ставить атрибут `type`, потому что у всех браузеров разное дефолтное значение для него. `button type="button"`

2021-10-15 16:21 UTC, nickchamel commented on src/utils/HTTPRequest.ts
> +                    reject(xhr.response);
Вот здесь можно парсить респонс, перед тем как резолвить или реджектить. 
А ниже где `xhr.send(data)` можно стрингифаить данные. Только нужно учесть еще multipart/form-data и тп

2021-10-20 12:46 UTC, iamkirabond commented
> Привет! Есть еще над чем поработать: При перезагрузке страниц они должны работать (это настройки netlify.toml - нужно чтобы всегд отдавался index.html) ![image](https://user-images.githubusercontent.com/28347933/137519832-e3043b88-864c-41bd-8cfd-ada7db7cf89d.png) Множественные ошибки в консоли (чаты не работают, сообщения не показываются) ![image](https://user-images.githubusercontent.com/28347933/137520017-44ea174a-a9c6-4ef0-bca0-354cae38c323.png) Аватар не грузится (ошибки в консоли) ![image](https://user-images.githubusercontent.com/28347933/137520191-3150781a-fec9-4285-9ab4-f15d887bce34.png) Изменить данные профиля не получается Перейти назад из профиля не получается Ошибки не показываются ![image](https://user-images.githubusercontent.com/28347933/137520319-a012966e-9f3a-4ba3-811c-3a25037792d9.png) Кнопка "авторизоваться не работает" Проверь, пожалуйста, что весь основной функционал работает перед отправкой на ревью! Еще стоит отметить что типизации нет совсем, было бы неплохо покрыть код типами. И тестов маловато, как минимум по заданию нужны еще на компонент и на http сервис Работу пока вернул

Привет, Никита!
спасибо за подробный разбор
скажу сразу, код буду переписывать в случае если все-таки пойду в академ, а пока решила исправить все критические недоработки

нетлифай теперь не падает с ошибкой при перезагрузке

ошибок в консоли теперь нет, новые сообщения показываются, но старые еще не подгружаются

аватар так и не грузится, хотя я уже и код в точности из урока взяла (Help!)
но если возвращается из апи, то все ок

на странице профиля такая логика, открывается сразу профиль с возможность править, т.е. /профиль -> меняем что то -> изменить данные -> данные отправляются на сервер -> при обновлении страницы все подтягивается сразу

страница входа теперь пускает, если уже есть регистрация, ранее была доп. проверка, теперь убрала ее

тесты дописала
запросы тестируются на https://jsonplaceholder.typicode.com/
роутер тесты тоже есть, но они падают с ошибкой, дальше нее пока не удалось продвинуться
<img width="510" alt="Screenshot 2021-10-20 at 15 45 49" src="https://user-images.githubusercontent.com/28915924/138095321-3257b90a-7c21-4620-8593-cd4c7da3dbe0.png">

спасибо,
Кира

2021-10-21 11:44 UTC, nickchamel reviewed
Привет! Код переписывать никто и не требует! Но для принятия работы необходимо, чтобы весь основной функционал работал.
У тебя сейчас даже залогиниться не получается и зарегистрироваться...
![image](https://user-images.githubusercontent.com/28347933/138267554-100848f0-d396-4f58-9bef-a32ab547c593.png)
Тут проблема в том, что ты несколько раз делаешь JSON.stringify. Из-за этого соответствующая ошибка с бэка: `Wrong json format`. Как и писал лучше один раз делать стрингифай на уровне `HTTPrequest`. А в контроллерах/апи просто пробрасывай данные. Когда это исправишь все основное заработает, затем чтобы заработал аватар нужно будет дописать в `HTTPrequest`:
```
if (isGet || !data) {
    xhr.send();
} else {
    if (data instanceof FormData) {
        xhr.send(data);
    } else {
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send(JSON.stringify(data));
    }
}
```
Когда отправляешь FormData не нужно ставить хедер `'Content-Type', 'application/json'` и не нужно модифицировать `data`
Тогда аватар заработает.
По поводу сообщений - это основа этого спринта. Сообщения должны отправляться и подгружаться. Ты можешь решить уйти в академ, можешь попробовать успеть доделать, но пожалуйста, убедись что основной функционал работает!
Но вообще после этого спринта уже будет легче намного!
По поводу теста - он не как сборщик, он работает только с JS грубо говоря, он не знает про scss и не может его обработать. Страницы нужно мокать в тесте. У тебя там переход на 404 и он пытается отрендерить эту страницу, а в ней подключается scss и он не понимает что нужно делать. Поэтому страницы нужно замокать в тесте.
Работу пока вернул

2021-10-21 19:50 UTC, iamkirabond commented
Привет! 

Спасибо за твой коммент, очень помог разобраться!
stringify поудаляла, аватар обновляется, страницы входа и чатов работают(проверяла сразу на нетлифае), в чатах грузятся последние 20 сообщений, тесты самые простые, но написала.

2021-10-22 06:23 UTC, nickchamel commented
Привет! Отлично. Молодец)
Оставлю тебе еще пару моментов, которые заметил: `Имя` в профиле отображается как имя в чате, а `Имя в чате` в профиле нет - короче говоря спутано местами. Еще из профиля нельзя перейти назад, кликая по стрелке (только большой элемент кликабельный, но не стрелка)
А так, в основном все хорошо работает, работу принял. Успехов в дальнейшем!

2021-11-03 15:30 UTC, merged